from pydantic import BaseModel, ConfigDict, Field
import uuid
import time
import json
from datetime import datetime
from zoneinfo import ZoneInfo

from constants import DISPLAY_TIMEZONE
from enum import StrEnum
from typing import Any


class CustomBaseModel(BaseModel):
    """Base model with common fields."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    created_at: float = Field(default_factory=time.time)
    updated_at: float = Field(default_factory=time.time)

    model_config = ConfigDict(
        populate_by_name=True,
        arbitrary_types_allowed=True,
        extra="allow",
        validate_assignment=False,
    )


# unix
class ChatTimeframe(BaseModel):
    start: int
    end: int

    def to_datetime(self):
        return {"start_date": datetime.fromtimestamp(self.start, tz=ZoneInfo(DISPLAY_TIMEZONE)), "end_date": datetime.fromtimestamp(self.end, tz=ZoneInfo(DISPLAY_TIMEZONE))}


class Message(BaseModel):
    id: str
    timestamp: int
    sender_id: str
    replies_to: str | None  # message.id
    content: str


class ModelEncoder(json.JSONEncoder):
    def default(self, obj):
        if hasattr(obj, "model_dump"):
            return obj.model_dump()
        return super().default(obj)


class DiscussionTypes(StrEnum):
    PRIMARY = "PRIMARY"
    SECONDARY = "SECONDARY"
    ONE_LINER = "ONE_LINER"


class LinkData(BaseModel):
    link: str
    discussion_substring: str


class Discussion(BaseModel):
    id: str = Field(description="The id of the discussion, generated by an llm", default="")
    group_name: str = Field(description="The name of the group the discussion belongs to", default="")
    title: str = Field(description="The title of the discussion", default="")
    messages: list[Message] = Field(description="A sorted list of the messages that belong to the discussion, oldest one on index 0", default=[])
    nutshell: str = Field(description="A short summary of the discussion", default="")
    num_messages: int = Field(description="The number of messages in the discussion", default=0)
    first_message_in_discussion_timestamp: int = Field(
        description="The unix timestamp of the first message in the discussion, taken from the Message timestamp attribute",
        default=0,
    )


class DiscussionSummarizedContent(BaseModel):
    content: list[str] | str = []
    links: list[LinkData] = []


class GroupDiscussions(BaseModel):
    group_name: str = ""
    parsed_messages_json_file_path: str = ""
    parsed_messages: list[Message] = []
    separate_discussions: list[Discussion] = []
    discussion_summaries: dict[str, DiscussionSummarizedContent] = Field(description="The summaries of the discussions", default_factory=dict)
    ranked_discussions: dict[DiscussionTypes, str] = Field(description="Ranking of each discussion - the value being the discussion id", default=[])
    number_of_messages: int | None = 0


class ChatAnalysisState(BaseModel):
    summary_headline: str = ""
    group_names: list[str] = []
    temp_for_dev_saved_json_file_path: str = ""
    days_per_summary: int = 14
    source_documents: list[Any] = []  # LlamaIndex Document objects (not filesystem files)
    discussions_by_group: dict[str, GroupDiscussions] = {}


######################## LLM SCHEMAS ########################


class ImageMetadata(BaseModel):
    """Metadata for an image extracted from a WhatsApp message."""

    image_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    mxc_url: str
    mimetype: str = ""
    width: int | None = None
    height: int | None = None
    size_bytes: int | None = None
    filename: str = ""
    sender_id: str = ""
    timestamp: int = 0
    message_id: str = ""
    chat_name: str = ""
    data_source_name: str = ""
    storage_path: str | None = None
    description: str | None = None
    description_model: str | None = None
    discussion_id: str | None = None

    # Matrix E2EE encryption fields (for decrypting encrypted media)
    encryption_key: str | None = None  # AES-CTR JWK key (content.file.key.k)
    encryption_iv: str | None = None  # Base64 AES-CTR IV (content.file.iv)
    encryption_sha256: str | None = None  # Base64 SHA-256 hash (content.file.hashes.sha256)


class ImageExtractionStats(BaseModel):
    """Statistics from the image extraction node."""

    enabled: bool = False
    total_images_found: int = 0
    images_downloaded: int = 0
    images_described: int = 0
    download_failures: int = 0
    vision_failures: int = 0


class LlmResponseInitialExtraction(BaseModel):
    messages: list[Message]
    sender_map: dict[str, str] = Field(default_factory=dict, description="Map of real sender names to anonymized sender_ids")


class TranslatedMessage(BaseModel):
    message: str
    id: str


class LlmResponseTranslateMessages(BaseModel):
    messages: list[TranslatedMessage]


class LlmResponseTranslateSummary(BaseModel):
    summary: str


class LlmResponseSeparateDiscussions(BaseModel):
    discussions: list[Discussion]


class LlmResponseDiscussionRanking(BaseModel):
    primary_discussion_id: str = Field(description="The id of the primary discussion, the single most valuable and innovative discussion for a GenAI engineer.")
    secondary_discussions_ids: list[str] = Field(description="The ids of the secondary discussions, no more than 4 of such discussions.")
    one_liners_ids: list[str] = Field(description="The ids of the one-liner discussion points, no more than 5 of such.")


class LlmResponseDiscussionSummary(BaseModel):
    bullet_points: list[str] = Field(description="The bullet points of the primary discussion, each one representing a key point of the discussion. Primary Discussion Must be exactly 5 bullet points, no more no less. Secondary Discussion Must be exactly 3 bullet points, no more no less. One-liner Discussion Must be exactly 1 bullet point, no more no less.")


class LlmResponseNewsletterSummary(BaseModel):
    markdown_content: str = Field(description="The complete newsletter content in valid Markdown format")
    sections: dict[str, str] = Field(description="Individual sections of the newsletter with keys matching the section names", default_factory=dict)
    industry_updates: str = Field(description="Announcements or updates from companies/services — new agent releases, expanded model capabilities, etc.", default="")
    tools_mentioned: str = Field(description="Names of tools, projects, extensions, SDKs, or repositories with relevant details and links", default="")
    work_practices: str = Field(description="Best practices, efficient workflows, tool combinations, and experience-based tips", default="")
    security_risks: str = Field(description="Security concerns, warnings, unsafe practices, mitigation proposals", default="")
    valuable_posts: str = Field(description="Links to blogs, videos, articles, documentation with explanation of their value and content", default="")
    open_questions: str = Field(description="Unanswered questions, areas needing further investigation, exploration topics - detailed explanations", default="")
    conceptual_discussions: str = Field(description="Architectural discussions, visionary ideas, disagreements on approaches, future directions - detailed explanations", default="")
    issues_challenges: str = Field(description="Bugs, field problems, unexpected behaviors, debugging approaches, solutions when available - detailed explanations", default="")
